const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    checkStoredLicense: () => ipcRenderer.invoke('check-stored-license'),
    loginRequest: (key, remember) => ipcRenderer.invoke('login-request', { licenseKey: key, rememberMe: remember }),
    autoLoginRequest: () => ipcRenderer.invoke('auto-login-request'),
    downloadFileFromUrl: (url) => ipcRenderer.send('download-file-from-url', url),
    openExternalLink: (url) => ipcRenderer.send('open-external-link', url),
    cancelDownload: () => ipcRenderer.send('cancel-download'),
    onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (event, data) => callback(data)),
    onDownloadComplete: (callback) => ipcRenderer.on('download-complete', callback),
    onDownloadCancelled: (callback) => ipcRenderer.on('download-cancelled', callback),
    logoutRequest: () => ipcRenderer.send('logout-request'),
    runToolAsAdmin: (toolName) => ipcRenderer.send('run-tool-as-admin', toolName),
    runSmartDiagnostics: () => ipcRenderer.invoke('run-smart-diagnosis'),
    checkForUpdates: () => ipcRenderer.send('check-for-updates'),
    onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_, data) => cb(data)),
    onSystemStats: (callback) => ipcRenderer.on('system-stats', (event, data) => callback(data)),
    getSystemUsage: () => ipcRenderer.invoke('get-system-usage'),
    sendDialogResponse: (response) => ipcRenderer.send('dialog-response', response),
    onStartLoginCheck: (callback) => ipcRenderer.on('start-login-check', callback),
    onLoginSuccessful: (callback) => ipcRenderer.on('login-successful', (event, data) => callback(data)),
    onSystemInfo: (callback) => ipcRenderer.on('system-info', (event, data) => callback(data)),
    getHwid: () => ipcRenderer.invoke('get-hwid'),
    getAppVersion: () => ipcRenderer.invoke('get-app-version'),
    onPlayLoginSound: (callback) => ipcRenderer.on('play-login-sound', callback),
    onForceLogout: (callback) => ipcRenderer.on('force-logout', callback),
    askAI: (message) => ipcRenderer.invoke('ask-ai', message),
    openPaymentWindow: () => ipcRenderer.send('open-payment-window'),
    initiateRealPayment: (data) => ipcRenderer.send('initiate-real-payment', data),
    sendActivationEmail: (payload) => ipcRenderer.invoke('send-activation-email', payload),
    minimizeWindow: () => ipcRenderer.send('window-minimize'),
    closeWindow: () => ipcRenderer.send('window-close'),
});