
[Configurations]
Lang = EN
PosX = 144
PosY = 310
Server = 1
DarkTheme = 1
ServerTxt = kms.loli.best
PortTxt = 1688
clearKMS = 0
RestoreKMS = 0
RNDIP = 0
KMSVer = 0
AllSetKeys = 1
OSPP = 
; ------------------------------------------------------------
;  www.defense.gov = 184.25.56.139, www.whitehouse.gov = 184.27.36.110, www.kremlin.ru = 95.173.136.72   ;)
FAKE_IP = 
; ------------------------------------------------------------
StartWindow = 1
Auto = 1
SECOPatcher = 0
Hook = 0
TAP = 0
Digital = 1
HWID = 1
KMS38 = 0
; ------------------------------------------------------------
OINSTALL = PENvbmZpZ3VyYXRpb24+DQogIDxBZGQgT2ZmaWNlQ2xpZW50RWRpdGlvbj0iMzIiIENoYW5uZWw9IkRvZ2Zvb2REZXZNYWluIj4NCiAgICA8UHJvZHVjdCBJRD0iUHJvUGx1czIwMjRWb2x1bWUiIFBJREtFWT0iMlREUFctTkRRN0ctRk1HOTktRFhRN00tVFgzVDIiPg0KICAgICAgPExhbmd1YWdlIElEPSJlbi11cyIgLz4NCiAgICA8L1Byb2R1Y3Q+DQogICAgPFByb2R1Y3QgSUQ9IlByb2plY3RQcm8yMDI0Vm9sdW1lIiBQSURLRVk9IkQ5R1RHLU5QN0RWLVQ2SlAzLUI2QjYyLUpCODlSIj4NCiAgICAgIDxMYW5ndWFnZSBJRD0iZW4tdXMiIC8+DQogICAgPC9Qcm9kdWN0Pg0KICAgIDxQcm9kdWN0IElEPSJWaXNpb1BybzIwMjRWb2x1bWUiIFBJREtFWT0iWVc2NlgtTkg2Mk0tRzZZRlAtQjdLQ1QtV1hHS1EiPg0KICAgICAgPExhbmd1YWdlIElEPSJlbi11cyIgLz4NCiAgICA8L1Byb2R1Y3Q+DQogICAgPFByb2R1Y3QgSUQ9IlByb29maW5nVG9vbHMiPg0KICAgICAgPExhbmd1YWdlIElEPSJlbi11cyIgLz4NCiAgICA8L1Byb2R1Y3Q+DQogIDwvQWRkPg0KICA8RGlzcGxheSBMZXZlbD0iRnVsbCIgQWNjZXB0RVVMQT0iVFJVRSIgLz4NCiAgPFVwZGF0ZXMgRW5hYmxlZD0iVFJVRSIgLz4NCiAgPFByb3BlcnR5IE5hbWU9IkFVVE9BQ1RJVkFURSIgVmFsdWU9IjEiIC8+DQo8L0NvbmZpZ3VyYXRpb24+DQo8IS0tICBPSW5zdGFsbFNldHRpbmcgQnJhbmNoPTEgIC0tPg0KPCEtLSAgT0luc3RhbGxTZXR0aW5nIE9mZmljZT0wICAtLT4NCjwhLS0gIE9JbnN0YWxsU2V0dGluZyBBcmNoPTAgIC0tPg0KPCEtLSAgT0luc3RhbGxTZXR0aW5nIFJlZGFjdD0yICAtLT4NCjwhLS0gIE9JbnN0YWxsU2V0dGluZyBQcm9kdWN0PTAgIC0tPg0KPCEtLSAgT0luc3RhbGxTZXR0aW5nIFVzZU9EVD0wICAtLT4NCjwhLS0gIE9JbnN0YWxsU2V0dGluZyBVc2VEYXJrVGhlbWU9MCAgLS0+DQo8IS0tICBPSW5zdGFsbFNldHRpbmcgVXNlRGFya1RoZW1lQmFja0NvbG9yPTM3LDM3LDM3ICAtLT4NCjwhLS0gIE9JbnN0YWxsU2V0dGluZyBSdW5Bc1RJPTAgIC0tPg0KPCEtLSAgT0luc3RhbGxTZXR0aW5nIFBBVEg9ICAtLT4NCjwhLS0gIE9JbnN0YWxsU2V0dGluZyBBcmlhMiBDb21tYW5kIExpbmU9LXMxMCAteDEwIC1qMTAgLW02MCAtdDIwIC1rMTBNIC1SIC1jIC0tcmV0cnktd2FpdD01IC0tY2hlY2stY2VydGlmaWNhdGU9ZmFsc2UgLS1maWxlLWFsbG9jYXRpb249ZmFsbG9jIC0tbWF4LW92ZXJhbGwtZG93bmxvYWQtbGltaXQ9MCAgLS0+DQo8IS0tICBPSW5zdGFsbFNldHRpbmcgQXJpYTIgQ29tbWFuZCBMaW5lMj0tczEgLWoxIC1SIC0tY2hlY2stY2VydGlmaWNhdGU9ZmFsc2UgLS1maWxlLWFsbG9jYXRpb249ZmFsbG9jIC1jICAtLT4NCjwhLS0gIE9JbnN0YWxsU2V0dGluZyBEb3dubG9hZCBmaWxlcyBpbiBvbmUgc3RyZWFtPTAgIC0tPg0KPCEtLSAgT0luc3RhbGxTZXR0aW5nIERvd25sb2FkIFZlcnNpb249MTYuMC4xMjUyNy4yMjI4NiAgLS0+DQo8IS0tICBPSW5zdGFsbFNldHRpbmcgTGFuZyBlbi1VUyAgLS0+DQoA
; ------------------------------------------------------------
[KMS Settings]
AI = 43200
RI = 43200
Log = 1
IP = 1
HWidIndex = 0
WinPIDIndex = 0
O15PIDIndex = 0
O16PIDIndex = 0
O14PIDIndex = 0
; ------------------------------------------------------------
[KMS Server]
Item0 = kms.loli.best
Item1 = kms.digiboy.ir
Item2 = kms.cgtsoft.com
Item3 = kms.sixyin.com
Item4 = kms.000606.xyz
Item5 = kms.jm33.me
Item6 = kms.kmzs123.cn
Item7 = kms.sdit163.com
Item8 = xincheng213618.cn
Item9 = kms.myds.cloud
Item10 = kms.catqu.com
Item11 = kms.ghpym.com
Item12 = kms.mc06.net
Item13 = kms.moeyuuko.top
Item14 = kms8.MSGuides.com
Item15 = kms9.MSGuides.com
Item16 = xykz.f3322.org
Item17 = kms.ddns.net
